BSRD-629: Move invoke tasks in a separate package
camptocamp/odoo-project-tasks pull request #1
Opened 2023-03-28 14:04 UTC by yankinmax

https://jira.camptocamp.com/browse/BSRD-629

2023-03-28 14:11 UTC, yankinmax commented on tasks/main.py
> +        return core_args + extra_args
here we can provide arguments for commands

2023-03-30 11:25 UTC, simahawk requested changes

2023-03-30 11:25 UTC, simahawk commented on setup.py
> +    keywords="invoke-cli",
```suggestion
    keywords="odoo-tools-cli",
```

2023-03-30 11:25 UTC, simahawk commented on HISTORY.rst
> +.. :changelog:
I would remove this file and let [towncrier](https://pypi.org/project/towncrier/) to the job w/ commit msgs

2023-03-30 11:25 UTC, simahawk commented on .pre-commit-config.yaml
> +files: ^tasks/
please include these changes

https://github.com/camptocamp/odoo-template/pull/646
https://github.com/camptocamp/odoo-template/pull/678

2023-03-30 14:49 UTC, yankinmax commented
@simahawk I've mostly updated with your suggestions. I don't know how towncrier works or how to check if it's working. I added needed files. It would be next step, I would say.
@gurneyalex I've checked all tasks. Only on few I have questions. See https://jira.camptocamp.com/browse/BSRD-629

I think this PR as the first step could be merged as it's. Then probably we can create separate cards about tasks to fix. Also I pointed to the fact that scripts should be checked after we have new directory structure. This was tested on current structure and we have a lot of code snippets with hardcoded `odoo/local-src`, `odoo/external-src` etc.

2023-03-31 07:15 UTC, merged